server:
  port: 8888
  tomcat:
    max-http-form-post-size: 4MB
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.41.204:3306/blueprint?useUnicode=true&characterEncoding=utf-8
    username: root
    password: "Test980120"